### ISSUE TITLE
Bug comment

### ISSUE THREAD

**Issue by epatrizio** [epatrizio/ola#4]
A comment on the last line causes an error : 
`Fatal error: exception Assert_failure("src/lexer.ml", 155, 9)`

**Comment by zapashcanon** [comment]
@epatrizio I guess you did not intend to close this.

**Comment by epatrizio** [comment]
Yes, that's this one.
If you're referring to the return statement problem, it's still open.

**Comment by zapashcanon** [comment]
Oh indeed, sorry, I look at your commit too quickly.
